### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by q2dg** [heuermh/gamepad-processing#1]
Last commit was far ago...and Processing 3 is here!

**Comment by heuermh** [comment]
Yes, it works fine under Processing 3 and in fact is available in the Processing 3 library manager.

**Comment by q2dg** [comment]
Ok, thanks a lot for your answer.
I'll close this issue, then.
Sorry for the inconvenience

**Comment by heuermh** [comment]
No problem!  If you find any issues or have any feature requests, please post them here.
